# Generated by Django 4.2 on 2023-04-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=400)),
                ('title', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=2000)),
                ('url', models.CharField(max_length=800)),
                ('image', models.CharField(blank=True, max_length=800)),
                ('price', models.FloatField()),
                ('status', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
    ]
