# Generated by Django 4.2 on 2023-04-16 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_created_at_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 16, 16, 10, 22, 293104, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 16, 16, 10, 22, 293147, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
